In [3]:
#201400302 홍민기
from keras.datasets import mnist
import numpy as np
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

def naive_relu(x):
    assert len(x.shape) == 2 #┈┈ x는 2D 넘파이 배열입니다.

    x = x.copy() #┈┈ 입력 텐서 자체를 바꾸지 않도록 복사합니다. for i in range(x.shape[0]):
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] = max(x[i, j], 0)
    return x
x = np.array([[1,2]])
print(naive_relu(x))


Using TensorFlow backend.


[[1 2]]


In [4]:
my_slice = test_images[:, 7:, 7:]
import matplotlib.pyplot as plt 
plt.imshow(my_slice[0], cmap=plt.cm.binary) 
plt.show()

<Figure size 640x480 with 1 Axes>

In [5]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2 #┈┈ x는 2D 넘파이 배열입니다. 
    assert len(y.shape) == 1 #┈┈ y는 넘파이 벡터입니다. 
    assert x.shape[1] == y.shape[0]
    
def naive_vector_dot(x, y):
    assert len(x.shape) == 1 #┈┈ x와 y는 넘파이 벡터입니다. assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]

    z = 0.
    for i in range(x.shape[0]): 
        z += x[i] * y[i]
    return z

def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2 #┈┈ x는 넘파이 행렬입니다. assert len(y.shape) == 1 ┈┈ y는 넘파이 벡터입니다.
    assert x.shape[1] == y.shape[0] #┈┈ x의 두 번째 차원이 y의 첫 번째 차원과 같아야 합니다!

    z = np.zeros(x.shape[0]) #┈┈ 이 연산은 x의 행과 같은 크기의 0이 채워진 벡터를 만듭니다. for i in range(x.shape[0]):
    for j in range(x.shape[1]): z[i] += x[i, j] * y[j]
    return z

In [6]:
x = np.array([[0., 1.],[2., 3.],[4., 5.]])
print(x.shape)

(3, 2)


In [7]:
x = x.reshape((6, 1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [8]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [9]:
x = np.zeros((300, 20)) #┈┈ 모두 0으로 채워진 (300, 20) 크기의 행렬을 만듭니다.
x = np.transpose(x)
print(x.shape)

(20, 300)
