In [2]:
import numpy as np
import scipy.special

actication_function=lambda x: 0.5*(x)

Input=np.array([0.9,0.1,0.8], ndmin=2).T
#Input=numpy.matrix([[0.9],[0.1],[0.8]])
print("input.T\n", Input)

Winput_hidden=np.matrix([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
print("Whidden_output\n", Whidden_output)

Xhidden=np.dot(Winput_hidden,Input)
print("Xhidden\n", Xhidden)

Ohidden=actication_function(Xhidden)
print("Ohidden\n", Ohidden)

Xoutput=np.dot(Whidden_output,Ohidden)
print("Xoutput\n", Xoutput)

output=actication_function(Xoutput)
print("output\n", output)

input.T
 [[0.9]
 [0.1]
 [0.8]]
Winput_hidden
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
Xhidden
 [[1.16]
 [0.42]
 [0.62]]
Ohidden
 [[0.58]
 [0.21]
 [0.31]]
Xoutput
 [[0.476]
 [0.515]
 [0.764]]
output
 [[0.238 ]
 [0.2575]
 [0.382 ]]
