In [1]:
# 201400302 홍민기
import numpy as np
import scipy.special

Winput_hidden=np.matrix([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
print("Whidden_output\n", Whidden_output)

targets = np.array([0.01, 0.01, 0.99], ndmin=2).T
output=np.array([0.238,0.2575,0.382], ndmin=2).T
Eoutput=np.absolute(output-targets)
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", Eoutput.sum())
#print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output.T / Whidden_output_sum1.T
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=np.dot(Whidden_output_norm,Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", Ehidden.sum())
#print("Ehidden_sum\n", sum(Ehidden))

Winput_hidden_sum1=Winput_hidden.sum(axis=1, dtype='float')
print("Winput_hidden_sum1\n", Winput_hidden_sum1)
Winput_hidden_norm=Winput_hidden.T / Winput_hidden_sum1.T
print("Winput_hidden_norm\n", Winput_hidden_norm)

Einput=np.dot(Winput_hidden_norm, Ehidden)
print("Einput\n", Einput)
print("Einput_sum\n", Einput.sum())
#print("Einput_sum\n", sum(Einput)) 

Winput_hidden
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
Eoutput
 [[0.228 ]
 [0.2475]
 [0.608 ]]
Eoutput_sum
 1.0835
Whidden_output_sum1
 [[1.5]
 [1.3]
 [1.8]]
Whidden_output_norm
 [[0.2        0.46153846 0.44444444]
 [0.46666667 0.38461538 0.05555556]
 [0.33333333 0.15384615 0.5       ]]
Ehidden
 [[0.43005299]
 [0.23537009]
 [0.41807692]]
Ehidden_sum
 1.0835
Winput_hidden_sum1
 [[1.6]
 [1.2]
 [1.2]]
Winput_hidden_norm
 [[0.5625     0.16666667 0.08333333]
 [0.1875     0.66666667 0.41666667]
 [0.25       0.16666667 0.5       ]]
Einput
 [[0.3159729 ]
 [0.41174704]
 [0.35578006]]
Einput_sum
 1.0835
