In [3]:
import numpy as np
import scipy.special

actication_function=lambda x: 0.5*(x)

Input=np.array([0.4,0.8], ndmin=2).T
print("input.T\n", Input)

Winput_hidden=np.matrix([[3.0,2.0],[1.0,7.0]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[2.0,3.0],[1.0,4.0]])
print("Whidden_output\n", Whidden_output)

Xhidden=np.dot(Winput_hidden,Input)
print("Xhidden\n", Xhidden)

Ohidden=actication_function(Xhidden)
print("Ohidden\n", Ohidden)

Xoutput=np.dot(Whidden_output,Ohidden)
print("Xoutput\n", Xoutput)

output=actication_function(Xoutput)
print("output\n", output)

input.T
 [[0.4]
 [0.8]]
Winput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Xhidden
 [[2.8]
 [6. ]]
Ohidden
 [[1.4]
 [3. ]]
Xoutput
 [[11.8]
 [13.4]]
output
 [[5.9]
 [6.7]]
