In [14]:
import numpy as np
import scipy.special

Winput_hidden=np.array([[3.0,2.0],[1.0,7.0]])
#Winput_hidden=np.matrix([[3.0,2.0],[1.0,7.0]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.array([[2.0,3.0],[1.0,4.0]])
#Whidden_output=np.matrix([[2.0,3.0],[1.0,4.0]])
print("Whidden_output\n", Whidden_output)

Target = np.array([6.7,7.2],ndmin=2).T
print("Target\n",Target)
output=np.array([5.9,6.7],ndmin=2).T
Eoutput=np.absolute(output-Target)
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", Eoutput.sum())
#print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output.T / Whidden_output_sum1.T
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=np.dot(Whidden_output_norm, Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", Ehidden.sum())
#print("Ehidden_sum\n", sum(Ehidden))

Winput_hidden_sum1=Winput_hidden.sum(axis=1, dtype='float')
print("Winput_hidden_sum1\n", Winput_hidden_sum1)
Winput_hidden_norm=Winput_hidden.T / Winput_hidden_sum1.T
print("Winput_hidden_norm\n", Winput_hidden_norm)

Einput=np.dot(Winput_hidden_norm, Ehidden)
print("Einput\n", Einput)
print("Einput_sum\n", Einput.sum())
#print("Einput_sum\n", sum(Einput))

Winput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Target
 [[6.7]
 [7.2]]
Eoutput
 [[0.8]
 [0.5]]
Eoutput_sum
 1.2999999999999998
Whidden_output_sum1
 [5. 5.]
Whidden_output_norm
 [[0.4 0.2]
 [0.6 0.8]]
Ehidden
 [[0.42]
 [0.88]]
Ehidden_sum
 1.2999999999999998
Winput_hidden_sum1
 [5. 8.]
Winput_hidden_norm
 [[0.6   0.125]
 [0.4   0.875]]
Einput
 [[0.362]
 [0.938]]
Einput_sum
 1.2999999999999998
