In [3]:
import numpy as np
import scipy.special

actication_function=lambda x: scipy.special.expit(x)

WInput_hidden=np.array([[3.0,2.0],[1.0,7.0]])
#WInput_hidden=np.matrix([[3.0,2.0],[1.0,7.0]])
print("WInput_hidden\n", WInput_hidden)

Whidden_output=np.array([[2.0,3.0],[1.0,4.0]])
#Whidden_output=np.matrix([[2.0,3.0],[1.0,4.0]])
print("Whidden_output\n", Whidden_output)

activation_function=lambda x: 0.5*(x)

Ohidden=np.array([0.4,0.5], ndmin=2).T
print("Ohidden\n", Ohidden)

Eoutput=np.array([0.8,0.5], ndmin=2).T
print("Eoutput\n", Eoutput)

WjkOj=np.dot(Whidden_output, Ohidden)
print("WjkOj\n", WjkOj)

delEoverdelWjk = -np.dot(Eoutput*0.5, Ohidden.T)
print("delEoverdelWjk\n",delEoverdelWjk)
Whidden_output = Whidden_output - (0.1 * delEoverdelWjk)
print("new Whidden_output\n", Whidden_output)


WInput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Ohidden
 [[0.4]
 [0.5]]
Eoutput
 [[0.8]
 [0.5]]
Eoutput_sum
 [1.3]
WjkOj
 [[2.3]
 [2.4]]
delEoverdelWjk
 [[-0.16  -0.2  ]
 [-0.1   -0.125]]
new Whidden_output
 [[2.016  3.02  ]
 [1.01   4.0125]]
