In [2]:
#201400302 홍민기 1. 2A, transpose of A, inverse of A를 쓰시오. 또한 A의 계수(rank)를 쓰시오
import numpy as np
A = np.array([[1,-2,3,5],[2,2,-1,0],[3,0,1,2],[1,0,2,0]])
print(A)

[[ 1 -2  3  5]
 [ 2  2 -1  0]
 [ 3  0  1  2]
 [ 1  0  2  0]]


In [3]:
print(2*A)

[[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]


In [4]:
AT=np.transpose(A)
print(AT)

[[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]


In [5]:
InverseA=np.linalg.inv(A)
print(InverseA)

[[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]


In [6]:
print(np.linalg.matrix_rank(A))


4


In [7]:
B=np.matrix([[1,-2,3,5],[2,2,-1,0],[3,0,1,2],[1,0,2,0]])
print(B)
print(type(A),type(B))
print(np.linalg.matrix_rank(B))

[[ 1 -2  3  5]
 [ 2  2 -1  0]
 [ 3  0  1  2]
 [ 1  0  2  0]]
<class 'numpy.ndarray'> <class 'numpy.matrixlib.defmatrix.matrix'>
4
