In [1]:
#201400302 홍민기 5.놈을계산하시오
import numpy as np
xT=np.array([3, -4, -1.2, 0, 2.3])
print(xT)


[ 3.  -4.  -1.2  0.   2.3]


In [2]:
x=np.transpose(xT)
print(x)

[ 3.  -4.  -1.2  0.   2.3]


In [3]:
#1차노름
def norm1(x) :
    sum=0;
    for i in range(0,len(x)):
        sum = sum+abs(x[i])
    return sum
x_1norm = norm1(x)
print("1차 노름은", x_1norm)

#2차노름
x_2norm=np.linalg.norm(x)
print("2차 노름은", x_2norm)

#3차노름
def norm3(x) :
    sum=0;
    for i in range(0,len(x)):
        sum = sum+ x[i]**3
    if(sum<0):
        return -abs(sum)**(1.0/3.0)
    return sum**(1.0/3.0)
x_3norm = norm3(x)
print("3차 노름은", x_3norm)

#max노름
x_max= np.linalg.norm(x, np.inf)
print("최대노름은", x_max)

1차 노름은 10.5
2차 노름은 5.632938842203065
3차 노름은 -2.983651814846192
최대노름은 4.0


In [4]:
A = np.array([[2,1],[1,5],[4,1]])
print(A)

[[2 1]
 [1 5]
 [4 1]]


In [5]:
#프로베니우스 놈
print("프로베니우스 놈은", np.linalg.norm(A,'fro'))

프로베니우스 놈은 6.928203230275509
