In [1]:
#201400302 홍민기
import numpy as np
import scipy.special

Winput_hidden=np.matrix([[0.9,0.4],[0.2,0.2],[0.1,0.6]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.8,0.1,0.5]])
print("Whidden_output\n", Whidden_output)

targets = np.array([0.01, 0.99], ndmin=2).T
output=np.array([0.722,0.727], ndmin=2).T
Eoutput=np.absolute(output-targets)
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", Eoutput.sum())
#print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output.T / Whidden_output_sum1.T
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=np.dot(Whidden_output_norm,Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", Ehidden.sum())
#print("Ehidden_sum\n", sum(Ehidden))

Winput_hidden_sum1=Winput_hidden.sum(axis=1, dtype='float')
print("Winput_hidden_sum1\n", Winput_hidden_sum1)
Winput_hidden_norm=Winput_hidden.T / Winput_hidden_sum1.T
print("Winput_hidden_norm\n", Whidden_output_norm)

Einput=np.dot(Winput_hidden_norm, Ehidden)
print("Einput\n", Einput)
print("Einput_sum\n", Einput.sum())
#print("Einput_sum\n", sum(Einput)) 

Winput_hidden
 [[0.9 0.4]
 [0.2 0.2]
 [0.1 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.8 0.1 0.5]]
Eoutput
 [[0.712]
 [0.263]]
Eoutput_sum
 0.975
Whidden_output_sum1
 [[1.5]
 [1.4]]
Whidden_output_norm
 [[0.2        0.57142857]
 [0.46666667 0.07142857]
 [0.33333333 0.35714286]]
Ehidden
 [[0.29268571]
 [0.35105238]
 [0.3312619 ]]
Ehidden_sum
 0.9749999999999999
Winput_hidden_sum1
 [[1.3]
 [0.4]
 [0.7]]
Winput_hidden_norm
 [[0.2        0.57142857]
 [0.46666667 0.07142857]
 [0.33333333 0.35714286]]
Einput
 [[0.42547789]
 [0.54952211]]
Einput_sum
 0.9749999999999999
