In [4]:
# 201400302 홍민기
import numpy as np
import scipy.special

actication_function=lambda x: scipy.special.expit(x)

Input=np.array([0.9,0.8], ndmin=2).T
#Input=numpy.matrix([[0.9],[0.8]])
print("input.T\n", input)

Winput_hidden=np.matrix([[0.9,0.4],[0.2,0.2],[0.1,0.6]])

print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.8,0.1,0.5]])
print("Whidden_output\n", Whidden_output)

Xhidden=np.dot(Winput_hidden,Input)
print("Xhidden\n", Xhidden)

Ohidden=actication_function(Xhidden)
print("Ohidden\n", Ohidden)

Xoutput=np.dot(Whidden_output,Ohidden)
print("Xoutput\n", Xoutput)

output=actication_function(Xoutput)
print("output\n", output)

input.T
 <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x10b7f0048>>
Winput_hidden
 [[0.9 0.4]
 [0.2 0.2]
 [0.1 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.8 0.1 0.5]]
Xhidden
 [[1.13]
 [0.34]
 [0.57]]
Ohidden
 [[0.7558389 ]
 [0.58419052]
 [0.63876318]]
Xoutput
 [[0.95506662]
 [0.98247176]]
output
 [[0.72213297]
 [0.72759839]]
