In [1]:
import numpy as np
import scipy.special

actication_function=lambda x: scipy.special.expit(x)

WInput_hidden=np.array([[3.0,2.0],[1.0,7.0]])
#WInput_hidden=np.matrix([[3.0,2.0],[1.0,7.0]])
print("WInput_hidden\n", WInput_hidden)

Whidden_output=np.array([[2.0,3.0],[1.0,4.0]])
#Whidden_output=np.matrix([[2.0,3.0],[1.0,4.0]])
print("Whidden_output\n", Whidden_output)

activation_function=lambda x: scipy.special.expit(x)

Ohidden=np.array([0.4,0.5], ndmin=2).T
print("Ohidden\n", Ohidden)

print("logit(0.4)\n", scipy.special.logit(0.4))
print("logit(0.5)\n", scipy.special.logit(0.5))
Xhidden=np.array([scipy.special.logit(0.4),scipy.special.logit(0.5)], ndmin=2).T
print("Xhidden.T\n", Xhidden)

print("inv(WInput_hidden)\n", np.linalg.inv(WInput_hidden))

Input=np.dot(np.linalg.inv(WInput_hidden), Xhidden)
#Input=np.array([-0.14938188,0.02134027], ndmin=2).T
#Input=np.matrix([[-0.14938188,0.02134027]])
print("Input\n", Input)
print("Input.T\n", Input.T)

Eoutput=np.array([0.8,0.5], ndmin=2).T
print("Eoutput\n", Eoutput)
print("Eoutput_sum\n", sum(Eoutput))

Whidden_output_sum1=Whidden_output.sum(axis=1, dtype='float')
print("Whidden_output_sum1\n", Whidden_output_sum1)
Whidden_output_norm=Whidden_output / Whidden_output_sum1
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden=np.dot(Whidden_output_norm.T, Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden_sum\n", sum(Ehidden))

WjkOj=np.dot(Whidden_output, Ohidden)
print("WjkOj\n", WjkOj)

S=activation_function(WjkOj)
print("S\n", S)

SS=np.multiply(S, (1.0 - S))
print("SS\n", SS)
PartialEoverPartialWjk = -np.dot(np.multiply(Eoutput, SS), Ohidden.T)
print("PartialEoverPartialWjk\n", PartialEoverPartialWjk)

Whidden_output = Whidden_output - (0.1 * PartialEoverPartialWjk)
print("new Whidden_output\n", Whidden_output)

WijOi=np.dot(WInput_hidden, Input)
#WijOi=np.dot(WInput_hidden, Input.T)
print("WijOi\n", WijOi)

S=activation_function(WijOi)
print("S\n", S)

SS=np.multiply(S, (1.0 - S))
print("SS\n", SS)

PartialEoverPartialWij = -np.dot(np.multiply(Ehidden, SS), Input.T)
#PartialEoverPartialWij = -np.dot(np.multiply(Ehidden, SS), Input)
print("PartialEoverPartialWij\n", PartialEoverPartialWij)

WInput_hidden = WInput_hidden - (0.1 * PartialEoverPartialWij)
print("new WInput_hidden\n", WInput_hidden)

WInput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Ohidden
 [[0.4]
 [0.5]]
logit(0.4)
 -0.4054651081081643
logit(0.5)
 0.0
Xhidden.T
 [[-0.40546511]
 [ 0.        ]]
inv(WInput_hidden)
 [[ 0.36842105 -0.10526316]
 [-0.05263158  0.15789474]]
Input
 [[-0.14938188]
 [ 0.02134027]]
Input.T
 [[-0.14938188  0.02134027]]
Eoutput
 [[0.8]
 [0.5]]
Eoutput_sum
 [1.3]
Whidden_output_sum1
 [5. 5.]
Whidden_output_norm
 [[0.4 0.6]
 [0.2 0.8]]
Ehidden
 [[0.42]
 [0.88]]
Ehidden_sum
 [1.3]
WjkOj
 [[2.3]
 [2.4]]
S
 [[0.90887704]
 [0.9168273 ]]
SS
 [[0.08281957]
 [0.076255  ]]
PartialEoverPartialWjk
 [[-0.02650226 -0.03312783]
 [-0.015251   -0.01906375]]
new Whidden_output
 [[2.00265023 3.00331278]
 [1.0015251  4.00190637]]
WijOi
 [[-4.05465108e-01]
 [ 2.77555756e-17]]
S
 [[0.4]
 [0.5]]
SS
 [[0.24]
 [0.25]]
PartialEoverPartialWij
 [[ 0.01505769 -0.0021511 ]
 [ 0.03286401 -0.00469486]]
new WInput_hidden
 [[2.99849423 2.00021511]
 [0.9967136  7.00046949]]
